### PR TITLE
Feature/sign up

### PR DESCRIPTION
**Pull request by alikheed256**

### CODE REVIEW

**Review by Peter-Kihoi — DISMISSED** [review]
Great

**Comment by alikheed256** [comment]
> _ No description provided. _

Admin web sign up page

**Review by rennison-kangethe — DISMISSED** [review]
great

**Review by maggywairigu — DISMISSED** [review]

**Review by abdiomari — DISMISSED** [review]

**Review by Peter-Kihoi — APPROVED** [review]
Done

**Review by maggywairigu — APPROVED** [review]

**Pull request merged**
